const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
const SIGN_OUT = 'SIGN_OUT';

const ASYNC_REQUEST = 'ASYNC_REQUEST';
const ASYNC_RECEIVE = 'ASYNC__RECEIVE';
const ASYNC_ERROR = 'ASYNC__ERROR';
const CLEAR_ASYNC_RESPONSE = 'CLEAR_ASYNC_RESPONSE';
const SHOW_USER_PROFILE = 'SHOW_USER_PROFILE';

//Constants for async response in the state
const SIGN_IN_SECTION = 'signIn';
const SIGN_UP_SECTION = 'signUp';
const CREATE_ALLIANCE_SECTION = 'createAlliance';
const ALLIANCES_SECTION = 'alliances';
const ALLIANCE_SECTION = 'alliance';
const SHOW_USER_SECTION = 'userProfile';

const SHOW_ALLIANCES = 'SHOW_ALLIANCES';
const SHOW_ALLIANCE = 'SHOW_ALLIANCE';
const SHOW_ALLIANCE_ERROR = 'SHOW_ALLIANCE_ERROR';
const SHOW_USER_PROFILE_ERROR = 'SHOW_USER_PROFILE_ERROR';

export { SIGN_OUT,
         UPDATE_USER_DATA,
         SHOW_USER_PROFILE,

         SIGN_IN_SECTION,
         SIGN_UP_SECTION,
         CREATE_ALLIANCE_SECTION,
         ALLIANCES_SECTION,
         ALLIANCE_SECTION,
         SHOW_USER_SECTION,

         ASYNC_REQUEST,
         ASYNC_RECEIVE,
         ASYNC_ERROR,
         CLEAR_ASYNC_RESPONSE,
         SHOW_ALLIANCES,
         SHOW_ALLIANCE,
         SHOW_ALLIANCE_ERROR,
         SHOW_USER_PROFILE_ERROR };