const UPDATE_USER_DATA = 'UPDATE_USER_DATA';

const ASYNC_REQUEST = 'ASYNC_REQUEST';
const ASYNC_RECEIVE = 'ASYNC__RECEIVE';
const ASYNC_ERROR = 'ASYNC__ERROR';
const CLEAR_ASYNC_RESPONSE = 'CLEAR_ASYNC_RESPONSE';

const USER_PROFILE_RECEIVE = 'USER_PROFILE_RECEIVE';
const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

//Constants for async response in the state
const SIGN_IN_SECTION = 'signIn';
const SIGN_UP_SECTION = 'signUp';
const CREATE_ALLIANCE_SECTION = 'createAlliance';
const ALLIANCES_SECTION = 'alliances';
const ALLIANCE_SECTION = 'alliance';
const USER_PROFILE_SECTION = 'userProfile';

const EDIT_ALLIANCE_SECTION = 'EDIT_ALLIANCE_SECTION';

const ALLIANCE_RECEIVE = 'ALLIANCE_RECEIVE';
const ALLIANCE_ERROR = 'ALLIANCE_ERROR';

const ALLIANCES_RECEIVE = 'ALLIANCES_RECEIVE';
const ALLIANCES_ERROR = 'ALLIANCES_ERROR';



export { UPDATE_USER_DATA,
         USER_PROFILE_RECEIVE,

         SIGN_IN_SECTION,
         SIGN_UP_SECTION,
         CREATE_ALLIANCE_SECTION,
         ALLIANCES_SECTION,
         ALLIANCE_SECTION,
         USER_PROFILE_SECTION,
         EDIT_ALLIANCE_SECTION,

         ASYNC_REQUEST,
         ASYNC_RECEIVE,
         ASYNC_ERROR,
         CLEAR_ASYNC_RESPONSE,

         ALLIANCES_RECEIVE,
         ALLIANCES_ERROR,

         ALLIANCE_RECEIVE,
         ALLIANCE_ERROR,
         USER_PROFILE_ERROR };